-- Grant needed privileges to app user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO paste;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO paste;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO paste;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO paste;
